config/routes.rb
Rails.application.routes.draw do
  resources :withdraws
  root 'home#index'
  resources :expenses
  resources :categories

  get '/month_expenses', to: "expenses#month_expenses", as: 'month_expenses'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :expenses, dependent: :destroy
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :category

  def self.get_current_month_expenses
    month = Date.today.month
    year = Date.today.year
    get_month_expenses(month, year)
  end

  def self.get_month_expenses(month, year)
    Expense
    .where('extract(month from date) = ? and extract(year from date) = ?', month, year)
    .group(:category)
    .sum(:amount)
  end

  def to_s
    "#{self.date} #{self.amount} #{self.category_id}"
  end
end

app/models/withdraw.rb
class Withdraw < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_url
    else
      format.html { render :new  }
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to categories_url
    else
      format.html { render :edit  }
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:new, :edit]

  def index
    @expenses = Expense.all
            .sort_by { |x| x.date }
            .reverse
            .group_by { |x| x.date }
  end

  def show
  end

  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(expense_params)

    if @expense.save
      redirect_to expenses_url
    else
      format.html { render :new  }
    end
  end

  def edit
  end

  def update
    if @expense.update(expense_params)
      redirect_to expenses_url
    else
      format.html { render :edit  }
    end
  end

  def destroy
    @expense.destroy
    redirect_to expenses_url
  end

  def month_expenses
    @current_month_expenses = Expense.get_current_month_expenses
                                .sort_by { |k,v| -v }

    @total_month_expenses = @current_month_expenses
                                .map { |c,e| e }
                                .inject(0){ |sum,x| sum + x }
  end

  private
    def set_expense
      @expense = Expense.find(params[:id])
    end

    def set_categories
      @categories = Category.all
    end

    def expense_params
      params.require(:expense).permit(:date, :description, :amount, :category_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/withdraws_controller.rb
class WithdrawsController < ApplicationController

  before_action :set_withdraw, only: [:edit, :update, :destroy]

  def new
    @withdraw = Withdraw.new
  end

  def edit
  end

  def index
    @withdraws = Withdraw.all
  end

  def create
    @withdraw = Withdraw.new(withdraw_params)

    if @withdraw.save
      redirect_to withdraws_url
    else
      render :new
    end
  end

  def update
    if @withdraw.update(withdraw_params)
      redirect_to withdraws_url
    else
      render :new
    end
  end

  def destroy
    @withdraw.destroy
    redirect_to withdraws_url
  end

  private
    def set_withdraw
      @withdraw = Withdraw.find(params[:id])
    end

    def withdraw_params
      params.require(:withdraw).permit(:date, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/withdraws_helper.rb
module WithdrawsHelper
end

app/views/categories/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= form_for(@category, html: {role: "form"}) do |f| %>
        <% if @category.errors.any? %>
            <div class="alert alert-danger alert-dismissable" role="alert">
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <h4><%= pluralize(@category.errors.count, "error") %> prohibited this course from being saved:</h4>

              <ul>
                <% @category.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, required: true, class: 'form-control' %>
        </div>

        <div class="form-group">
          <div class=" col-sm-10">
            <%= f.submit class: "btn btn-primary" %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<%= link_to new_category_path do %>
  New
<% end %>

<h1>index</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |c| %>
      <tr>
        <td><%= c.name %></td>
        <td><%= link_to 'Edit', edit_category_path(c.id) %></td>
        <td><%= link_to 'Delete', c, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h1>Create category</h1>

<div class="card-body">
  <%= render 'form' %>
</div>

app/views/categories/show.html.erb
show

app/views/expenses/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= form_for(@expense, html: {role: "form"}) do |f| %>
        <% if @expense.errors.any? %>
            <div class="alert alert-danger alert-dismissable" role="alert">
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <h4><%= pluralize(@expense.errors.count, "error") %> prohibited this course from being saved:</h4>

              <ul>
                <% @expense.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="form-group">
          <%= f.label :category_id %>
          <%= f.select :category_id, @categories.map { |c| [c.name, c.id] }, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :date %>
          <%= f.date_select :date, required: true, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :amount%>
          <%= f.text_field :amount, required: true, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>

        <div class="form-group">
          <div class=" col-sm-10">
            <%= f.submit class: "btn btn-primary" %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/expenses/index.html.erb
<%= link_to new_expense_path do %>
  New
<% end %>

<h1>Index</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Date</th>
      <th>Category</th>
      <th>Amount</th>
      <th>Description</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @expenses.each do |k,v| %>
      <% v.each do |c| %>
    <tr>
      <td><%= c.date %></td>
      <td><%= c.category.name %></td>
      <td><%= c.amount %></td>
      <td><%= c.description %></td>
      <td><%= link_to 'Edit', edit_expense_path(c.id) %></td>
      <td><%= link_to 'Delete', c, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
      <% end %>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/expenses/month_expenses.html.erb
<h1>Month Expenses</h1>

<div class="card">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Category</th>
        <th>Amount</th>
      </tr>
    </thead>
    <tbody>
      <% @current_month_expenses.each do |key, value| %>
      <tr>
        <td><%= key.name %></td>
        <td><%= value %></td>
      </tr>
      <% end %>
      <tr>
        <td><strong>Total</strong></td>
        <td><strong><%= @total_month_expenses %></strong></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Expenses Tracker</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Home', '/', class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Categories', categories_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Expenses', expenses_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Month Expenses', month_expenses_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Withdraws', withdraws_path, class: 'nav-link'%>
      </li>
    </ul>
  </div>
</nav>

app/views/home/index.html.erb
<h1 class="display-1">Expenses Tracker v1.0</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpensesTracker</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<%= render 'home/navbar' %>
  <body>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/withdraws/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= form_for(@withdraw, html: {role: "form"}) do |f| %>
        <% if @withdraw.errors.any? %>
            <div class="alert alert-danger alert-dismissable" role="alert">
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <h4><%= pluralize(@withdraw.errors.count, "error") %> prohibited this course from being saved:</h4>

              <ul>
                <% @withdraw.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="form-group">
          <%= f.label :date %>
          <%= f.date_select :date, required: true, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :amount %>
          <%= f.text_field :amount, required: true, class: 'form-control' %>
        </div>

        <div class="form-group">
          <div class=" col-sm-10">
            <%= f.submit class: "btn btn-primary" %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/withdraws/edit.html.erb
<h1>Edit</h1>

<div class="card-body">
  <%= render 'form' %>
</div>

app/views/withdraws/index.html.erb
<%= link_to 'New', new_withdraw_path %>
<h1>Index</h1>

<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody>
    <% @withdraws.each do |w| %>
      <tr>
        <td><%= w.date %></td>
        <td><%= w.amount %></td>
        <td><%= link_to 'Edit', edit_withdraw_path(w.id) %></td>
        <td><%= link_to 'Delete', w, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/withdraws/new.html.erb
<h1>Create</h1>

<div class="card-body">
  <%= render 'form' %>
</div>